services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Service\:
    resource: '../src/Service/*'

  App\Helper\:
    resource: '../src/Helper/*'

  App\Repository\:
    resource: '../src/Repository/*'

  App\Service\FeeCalculatorService:
    arguments:
      $feeCalculatorRepository: '@App\Repository\InMemoryFeeStructureRepository'
      $feeInterpolatorHelper: '@App\Helper\FeeInterpolatorHelper'